services:
  - type: web
    name: folderagent
    env: node
    region: ohio
    plan: starter
    buildCommand: cd chat && npm install && npm run build
    startCommand: cd chat && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VECTORIA_INTERNAL_URL
        value: http://vectoria:10000
      - key: NEXT_PUBLIC_UPGRADE_URL
        value: http://upgrade-hwae:10000
      - key: NEXT_PUBLIC_UPGRADE_API_URL
        value: http://upgrade-hwae:10000
      - key: OPENAI_API_KEY
        sync: false # Indicates this is a secret value
      - key: BASE_PATH
        value: /chat
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
    healthCheckPath: /chat/health
    autoDeploy: true 